package net.herobrine.quirkbattle.game;

public enum CustomDeathCause {

    SHOOT_STYLE, DETRIOT_SMASH, ONE_FOR_ALL_SELF, GENERAL_ATTACK, OUTSIDE_MAP, EXPLOSION_DASH, EXPLOSION_PUNCH, HOWITZER_IMPACT, SHARP_CLAW, STONE_CHARGE;
}
