package net.herobrine.quirkbattle.game;

public enum CustomDeathCause {

    SHOOT_STYLE, DETRIOT_SMASH, ONE_FOR_ALL_SELF, GENERAL_ATTACK, OUTSIDE_MAP, EXPLOSION_DASH, EXPLOSION_PUNCH, HOWITZER_IMPACT, SHARP_CLAW, STONE_CHARGE, FROSTBITE, OVERHEAT,
    SHARPENED_KNIFE, ICE_WALL, ICE_SHARD,GLACIER,FLASHFIRE_FIST,FLAME_WALL,OVERDRIVE, RECIPRO_BURST, RAPID_KICK, TENDRIL,
    AIR_CANNON, BLOOD_NEEDLE, DECAY_TOUCH, DECAY_WAVE, DECAY_AURA, DISINTEGRATION, CREAMATION_BURST, BLUEFLAME_WALL, INCINERATE, TRANSMISSION, GEARSHIFT_OVERDRIVE;

    //TODO add death/kill message templates into this enum, so that we don't have to individually write them all in the listener.
}
