arenas:
  '5':
    spawn:
      world: 'myhero'
      x: 986.5
      y: 4
      z: 446.5
      pitch: 1
      yaw: -90
    team1spawn:
      world: 'myhero'
      x: 986.5
      y: 4
      z: -446.5
      pitch: 1
      yaw: -90
    team2spawn:
      world: 'myhero'
      x: 1093.5
      y: 4
      z: -446.5
      pitch: 1
      yaw: 90
    region:
      first-position:
        world: 'myhero'
        x: 986.0
        y: 3.0
        z: -476.0
      second-position:
        world: 'myhero'
        x: 1094.0
        y: 78.0
        z: -419.0